# Site settings
title: prx labs
email: chris@prx.org
description: "prx labs is the hub of technology and innovation at PRX, an award-winning public media company. "
description_html: "<a href='/about'>prx labs</a> is the hub of technology and innovation at <a href='http://prx.org'>PRX</a>, an award-winning public media company."
baseurl: ""
url: "http://github.prx.io"
twitter_username: prx
github_username:  PRX

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: <!--more-->
